{{- if .Values.preflight.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: kerno-preflight
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kerno.labels" . | nindent 4 }}
    app.kubernetes.io/component: preflight
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: kerno
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: preflight
          image: {{ include "kerno.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["preflight", "--output", "json"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: sys-kernel-btf
              mountPath: /sys/kernel/btf
              readOnly: true
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
              readOnly: true
            - name: proc
              mountPath: /proc
              readOnly: true
            - name: sys-fs-cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
      volumes:
        - name: sys-kernel-btf
          hostPath:
            path: /sys/kernel/btf
            type: Directory
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
            type: Directory
        - name: proc
          hostPath:
            path: /proc
            type: Directory
        - name: sys-fs-cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
{{- end }}
