{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kerno
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kerno.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kerno.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
{{- end }}
